### PR TITLE
Add snapshot

### PR DESCRIPTION
**Pull request by Fale**
Close bug #116

### CODE REVIEW

**Comment by grypyrg** [comment]
Great idea! 
Do you have a better snapshot which is more ~80x24 and more readable? It's hard to actually see it now.

**Comment by Fale** [comment]
80x24? Columns/lines?

**Comment by aioue** [comment]
How about this:

screen shot 2016-01-07 at 22 39 10

**Comment by aioue** [comment]
+1

**Comment by lefred** [comment]
Thank you for your contribution @Fale

**Pull request merged**
