### PR TITLE
Add information_schema/performance_schema handling for 8.0 lock_waits

### PR DESCRIPTION
**Pull request by yoku0825**
- https://github.com/innotop/innotop/issues/183

### CODE REVIEW

**Comment by yoku0825** [comment]
# vs MySQL 5.7 (no regression)

image


# vs MySQL 8.0 (fix issue)

image

**Comment by lefred** [comment]
Thank you for your PR.

On my system (8.0.25 on Linux) I get this issue:
Screenshot from 2021-06-16 10-06-09

It works if I rewrite your query like this:
`SELECT /*innotop*/
               r.trx_mysql_thread_id                            AS waiting_thread,
               r.trx_query                                      AS waiting_query,
               r.trx_rows_modified                              AS waiting_rows_modified,
               TIMESTAMPDIFF(SECOND, r.trx_started, NOW())      AS waiting_age,
               TIMESTAMPDIFF(SECOND, r.trx_wait_started, NOW()) AS waiting_wait_secs,
               rp.user                                          AS waiting_user,
               rp.host                                          AS waiting_host,
               rp.db                                            AS waiting_db,
               b.trx_mysql_thread_id                            AS blocking_thread,
               b.trx_query                                      AS blocking_query,
               b.trx_rows_modified                              AS blocking_rows_modified,
               TIMESTAMPDIFF(SECOND, b.trx_started, NOW())      AS blocking_age,
               TIMESTAMPDIFF(SECOND, b.trx_wait_started, NOW()) AS blocking_wait_secs,
               bp.user                                          AS blocking_user,
               bp.host                                          AS blocking_host,
               bp.db                                            AS blocking_db,
               CONCAT(bp.command, IF(bp.command = 'Sleep', CONCAT(' ', bp.time),   '')) AS blocking_status,
               CONCAT(lock_mode, ' ', lock_type, ' ', object_name, '(', index_name, ')') AS lock_info
            FROM performance_schema.data_lock_waits w
               JOIN INFORMATION_SCHEMA.INNODB_TRX b   ON  b.trx_id  = w.blocking_engine_transaction_id
               JOIN INFORMATION_SCHEMA.INNODB_TRX r   ON  r.trx_id  = w.requesting_engine_transaction_id
               JOIN performance_schema.data_locks l ON  l.engine_lock_id = w.requesting_engine_lock_id
               LEFT JOIN INFORMATION_SCHEMA.PROCESSLIST bp ON bp.id = b.trx_mysql_thread_id
               LEFT JOIN INFORMATION_SCHEMA.PROCESSLIST rp ON rp.id = r.trx_mysql_thread_id`

Could you test if it works on your system too ?

**Comment by yoku0825** [comment]
Woops, I found `lower_case_table_names = 1` in my.cnf ..
I fix them lower-case.

**Comment by msheung** [comment]
I think the sql is simpler if we get the lock waits information from sys.innodb_lock_waits like the one below:
 
select lw.waiting_pid, lw.waiting_query,wait_age, lw.blocking_pid, lw.blocking_trx_rows_modified, lw.blocking_trx_age, p.command, lw.blocking_query from sys.innodb_lock_waits lw, information_schema.processlist p where lw.blocking_pid = p.id;

pls confirm this will give same result.

**Pull request merged**
